name: Build, Publish & Release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    uses: codam-coding-college/release-config/.github/workflows/release.yml@main
    secrets: inherit
